# Generated by Django 5.0 on 2024-02-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movie_name_movie_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
